### ISSUE TITLE
Unable to create new newsletter document for non admin user

### ISSUE THREAD

**Issue by heigpa** [pimcore/newsletter-bundle#35]
I have set up a new non admin user with the following permissions:
- Pimcore Newsletter Bundle - Newsletter
- All document types
- All classes
- Workspace Permission for documents

After a login with this user, it is not possible  to create a new newsletter document. Looks like the permission is missing.

**Comment by kingjia90** [comment]
Luckily only the demos were affected, due a wrong value in the dump
