### ISSUE TITLE
Cannot use Default Object List as Address Source Adapter

### ISSUE THREAD

**Issue by breakone** [pimcore/newsletter-bundle#38]
I cannot use the "Default Object List" as "Address Source Adapter". Get the following error:

<img width="1563" alt="image" src="https://github.com/pimcore/newsletter-bundle/assets/4848121/23609c5f-0033-4968-8759-6a89bbbe5543">

**Comment by blankse** [comment]
@breakone I can't reproduce it. Do you still have the problem?

**Comment by mattamon** [comment]
@breakone any update on this?

**Comment by breakone** [comment]
@mattamon @blankse 
Sorry, I haven't had time to look at the problem again yet. But I'll do it soon. Let you know.

**Comment by blankse** [comment]
@breakone Any updates?

**Comment by breakone** [comment]
@blankse yep, sorry...was a problem with a JS override
